### PR TITLE
Update SFT Protocol icon

### PR DESCRIPTION
**Pull request by Sunnight-wj**
due to brand upgrade, we updated our project logo.

### CODE REVIEW

**Comment by Sunnight-wj** [comment]
Anyone can handle this PR？ @hmmdeif @nanthanwa @stefanofa @ChazSchmidt

**Comment by Define101** [comment]
Is there any public information regarding the brand upgrade?

**Comment by Define101** [comment]
Also i have no idea who are those 4 people

**Comment by nanthanwa** [comment]
> Also i have no idea who are those 4 people

they just do random tagging, which is so annoying
unsubscribed

**Comment by Sunnight-wj** [comment]
> > Also i have no idea who are those 4 people
> 
> they just do random tagging, which is so annoying unsubscribed

I am sorry to bother you!

**Comment by Sunnight-wj** [comment]
> Is there any public information regarding the brand upgrade?

@Define101 There is our community announcement: https://t.me/SFTprotocol_ann/326

**Pull request merged**
