### PR TITLE
Replaced Klaytn with Kaia logo

### PR DESCRIPTION
**Pull request by praveen-kaia**
Replaced Klaytn Logo with Kaia

### CODE REVIEW

**Comment by praveen-kaia** [comment]
Hi @realdealshaman , im so sorry. Looks like there is bit of confusion as only frontend related changes are made in defillama server code while addressing your review comments and this is the previous icons PR https://github.com/DefiLlama/icons/pull/1769 . 

So, now I have created a new PR replacing the existing Klaytn icon with Kaia logo to reflect in the chainlist frontend. Also added Testnet 1001 also to reflect the icon in the frontend. Could you please review the changes once. 

Thank you very much for your time.

**Comment by praveen-kaia** [comment]
Hi @realdealshaman , can you please check this PR and let me know if you need more info. Thank you !

**Comment by realdealshaman** [comment]
Hi @praveen-kaia sorry about the delay, I've updated the logo on chainlist already, if you don't see the new logo yet please hard refresh the page: ctrl+shift+R

Please let me know if everything is good now and if we can close this pr :pray:

**Comment by praveen-kaia** [comment]
Thanks much @realdealshaman . Appreciate your work 

Closing the current PR.

**Pull request closed without merging**
