### PR TITLE
Update powpeg fast mode protocol icon

### PR DESCRIPTION
**Pull request by ahsan-javaiid**
## Description

This Pr adds icon for powpeg fast mode protocol.

Protocol link: https://defillama.com/protocol/powpeg-fast-mode 
dApp: https://powpeg.rootstock.io/

### CODE REVIEW

**Comment by ahsan-javaiid** [comment]
cc: @realdealshaman for review.

**Comment by ahsan-javaiid** [comment]
cc: @Define101 for review

**Comment by ahsan-javaiid** [comment]
@Define101 would be great if you can merge this PR.

**Comment by realdealshaman** [comment]
@ahsan-javaiid should this be the logo 
image

**Comment by ahsan-javaiid** [comment]
> @ahsan-javaiid should this be the logo image

The logo used in the PR is the correct one. Using same logo used for powpeg bridge: https://defillama.com/bridge/rootstock-powpeg-bridge and powpeg dApp: https://powpeg.rootstock.io/

**Pull request merged**
